---
title: "Outline"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 

* Sequential bilinguals never reach their L1 proficiency in L2
* L2 processing is more costly
* Phonological mismatches are a source of this difficulty
* Some sounds in non-native speech do not clearly correspond to phonemes in the native repertoire
* Nonetheless, word recognition is possible even when listening to an unfamiliar language, provided sufficient phonological overlap
* Phonological similarity also helps proficient bilinguals translating words during translation
* In proficient bilinguals, it plays a lesser role, though, as they seem to relie more strongly on the conceptual route
* The informativeness of phonological overlap during translation has been largely underexplored
* Most studies have either focused on orthographic similarity (constrained by orthographic system) or highly proficient bilinguals (who rely less on lexical properties during translation)
* Translation elicitation task: we ask adult listeners to translate words from an unfamiliar language to their native language
* This ensures that phonological similarity is the only information they can rely on to translate words
* If phonological similarity by itself plays a central role in non-native speech perception, participants should benefit from phonological similarity


# Methods

* Participants
* Stimuli
	- Lexical frequency
	- Phonological neighbourhood density (PTHN)
	- Phonological similarity (Levenshtein distance)
* Procedure
* Data analysis
	- Dependent variable (response codings)
	- Predictors

# Results

* Model comparison
* Population-level effects
	- Group comparisons
* Group-level effects

# Discussion





